-- ═══════════════════════════════════════════════════════════════════════════
-- Teach AI for India — 0045 Optimize RLS policies (auth InitPlan caching)
--
-- Every policy predicate called auth.uid()/auth_role()/auth_campus()/is_admin()/
-- is_super_admin() unwrapped. Postgres/PostgREST re-evaluate an unwrapped
-- current-user function once PER ROW scanned, and every one of these helper
-- functions (0002_functions_triggers.sql) does its own `select ... from
-- public.users where id = auth.uid()` lookup — so an unwrapped policy adds a
-- users-table lookup per row to every filtered/joined query.
--
-- Wrapping the same call as `(select auth.uid())` lets Postgres evaluate it
-- once per statement (an InitPlan) and reuse the cached result for every row,
-- per Supabase's documented RLS performance guidance. All wrapped functions
-- are STABLE (same input -> same output within one statement), so this is a
-- pure performance change — policy semantics are unchanged.
--
-- `is_campus_lead_plus(campus_id)` (media_update) is intentionally left
-- unwrapped: its argument is the row's own campus_id, so the call is already
-- correlated per row and wrapping it in a subquery would not let Postgres
-- cache it as an InitPlan.
--
-- Generated by diffing pg_policies against the same mechanical rewrite,
-- applied only to policies whose predicate actually contains one of the
-- wrappable calls (59 of the 69 public-schema policies; the other 10 have
-- no auth-function calls at all, e.g. `using (true)`, and are untouched).
-- ═══════════════════════════════════════════════════════════════════════════

alter policy announcements_select on public.announcements using (((campus_id IS NULL) OR (select is_admin()) OR (campus_id = (select auth_campus()))));
alter policy announcements_write on public.announcements using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role, 'exec_lead'::user_role, 'volunteer_lead'::user_role])) AND (campus_id = (select auth_campus()))))) with check (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role, 'exec_lead'::user_role, 'volunteer_lead'::user_role])) AND (campus_id IS NOT NULL) AND (campus_id = (select auth_campus())))));
alter policy attendance_select on public.attendance_records using (((user_id = (select auth.uid())) OR (EXISTS ( SELECT 1
   FROM sessions s
  WHERE ((s.id = attendance_records.session_id) AND ((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'exec_lead'::user_role, 'volunteer_lead'::user_role])) AND (s.campus_id = (select auth_campus())))))))));
alter policy attendance_write on public.attendance_records using ((EXISTS ( SELECT 1
   FROM sessions s
  WHERE ((s.id = attendance_records.session_id) AND ((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'exec_lead'::user_role])) AND (s.campus_id = (select auth_campus())))))))) with check ((EXISTS ( SELECT 1
   FROM sessions s
  WHERE ((s.id = attendance_records.session_id) AND ((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'exec_lead'::user_role])) AND (s.campus_id = (select auth_campus()))))))));
alter policy audit_select on public.audit_log using ((select is_super_admin()));
alter policy budget_increase_requests_select on public.budget_increase_requests using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'finance_lead'::user_role, 'campus_mgmt_admin'::user_role])) AND (campus_id = (select auth_campus()))) OR (created_by = (select auth.uid()))));
alter policy budget_increase_requests_write on public.budget_increase_requests using ((select is_admin())) with check ((select is_admin()));
alter policy campus_budgets_select on public.campus_budgets using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'campus_mgmt_admin'::user_role, 'finance_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy campus_budgets_write on public.campus_budgets using ((select is_admin())) with check ((select is_admin()));
alter policy campuses_lead_update on public.campuses using ((((select auth_role()) = 'campus_lead'::user_role) AND (id = (select auth_campus())))) with check ((((select auth_role()) = 'campus_lead'::user_role) AND (id = (select auth_campus()))));
alter policy campuses_write on public.campuses using ((select is_admin())) with check ((select is_admin()));
alter policy certificates_select on public.certificates using (((volunteer_id = (select auth.uid())) OR (select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'volunteer_lead'::user_role, 'exec_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy certificates_write on public.certificates using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'volunteer_lead'::user_role])) AND (campus_id = (select auth_campus()))))) with check (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'volunteer_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy contact_manage on public.contact_messages using ((select is_admin())) with check ((select is_admin()));
alter policy contact_read on public.contact_messages using ((select is_admin()));
alter policy content_write on public.content_blocks using ((select is_admin())) with check ((select is_admin()));
alter policy execution_plans_select on public.execution_plans using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'exec_lead'::user_role, 'finance_lead'::user_role, 'campus_mgmt_admin'::user_role])) AND (campus_id = (select auth_campus()))) OR (created_by = (select auth.uid()))));
alter policy execution_plans_write on public.execution_plans using ((select is_admin())) with check ((select is_admin()));
alter policy media_delete on public.media_assets using ((select is_super_admin()));
alter policy media_insert on public.media_assets with check ((uploaded_by = (select auth.uid())));
alter policy media_select on public.media_assets using (((is_public AND (approval_status = 'approved'::approval_status) AND (deleted_at IS NULL)) OR (select is_admin()) OR ((deleted_at IS NULL) AND ((campus_id = (select auth_campus())) OR ((select auth_role()) = 'campus_lead'::user_role)))));
alter policy media_update on public.media_assets using (((select is_admin()) OR is_campus_lead_plus(campus_id) OR (uploaded_by = (select auth.uid())))) with check (((select is_admin()) OR is_campus_lead_plus(campus_id) OR (uploaded_by = (select auth.uid()))));
alter policy notif_delete on public.notifications using ((recipient_id = (select auth.uid())));
alter policy notif_select on public.notifications using ((recipient_id = (select auth.uid())));
alter policy notif_update on public.notifications using ((recipient_id = (select auth.uid()))) with check ((recipient_id = (select auth.uid())));
alter policy outreach_requests_select on public.outreach_requests using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role, 'campus_mgmt_admin'::user_role])) AND (campus_id = (select auth_campus()))) OR (created_by = (select auth.uid()))));
alter policy outreach_requests_write on public.outreach_requests using ((select is_admin())) with check ((select is_admin()));
alter policy outreach_visit_requests_select on public.outreach_visit_requests using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'finance_lead'::user_role, 'campus_mgmt_admin'::user_role, 'outreach_lead'::user_role])) AND (campus_id = (select auth_campus()))) OR (created_by = (select auth.uid()))));
alter policy outreach_visit_requests_write on public.outreach_visit_requests using ((select is_admin())) with check ((select is_admin()));
alter policy reimb_delete on public.reimbursements using ((select is_super_admin()));
alter policy reimb_insert on public.reimbursements with check (((claimant_id = (select auth.uid())) AND ((select auth_role()) = ANY (ARRAY['super_admin'::user_role, 'outreach_lead'::user_role, 'exec_lead'::user_role, 'volunteer'::user_role]))));
alter policy reimb_select on public.reimbursements using (((claimant_id = (select auth.uid())) OR (select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'volunteer_lead'::user_role, 'campus_mgmt_admin'::user_role, 'finance_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy reimb_update on public.reimbursements using (((select is_admin()) OR ((claimant_id = (select auth.uid())) AND (status = ANY (ARRAY['draft'::reimbursement_status, 'rejected'::reimbursement_status]))))) with check (((select is_admin()) OR ((claimant_id = (select auth.uid())) AND (status = ANY (ARRAY['draft'::reimbursement_status, 'submitted'::reimbursement_status, 'rejected'::reimbursement_status])))));
alter policy school_contacts_write on public.school_contacts using ((EXISTS ( SELECT 1
   FROM schools s
  WHERE ((s.id = school_contacts.school_id) AND ((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role])) AND (s.campus_id = (select auth_campus())))))))) with check ((EXISTS ( SELECT 1
   FROM schools s
  WHERE ((s.id = school_contacts.school_id) AND ((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role])) AND (s.campus_id = (select auth_campus()))))))));
alter policy ssh_insert on public.school_status_history with check ((EXISTS ( SELECT 1
   FROM schools s
  WHERE ((s.id = school_status_history.school_id) AND ((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role])) AND (s.campus_id = (select auth_campus()))))))));
alter policy school_visits_select on public.school_visits using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role, 'campus_mgmt_admin'::user_role])) AND (campus_id = (select auth_campus()))) OR (created_by = (select auth.uid()))));
alter policy school_visits_write on public.school_visits using ((select is_admin())) with check ((select is_admin()));
alter policy schools_delete on public.schools using ((select is_admin()));
alter policy schools_insert on public.schools with check (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy schools_update on public.schools using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role])) AND (campus_id = (select auth_campus()))))) with check (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy session_assignments_manage on public.session_assignments using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'volunteer_lead'::user_role])) AND (campus_id = (select auth_campus()))))) with check (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'volunteer_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy session_assignments_respond on public.session_assignments using ((volunteer_id = (select auth.uid()))) with check ((volunteer_id = (select auth.uid())));
alter policy session_assignments_select on public.session_assignments using (((select is_admin()) OR (volunteer_id = (select auth.uid())) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role, 'exec_lead'::user_role, 'volunteer_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy session_plans_select on public.session_plans using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role, 'exec_lead'::user_role, 'volunteer_lead'::user_role])) AND (campus_id = (select auth_campus()))) OR (created_by = (select auth.uid()))));
alter policy session_plans_write on public.session_plans using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role])) AND (campus_id = (select auth_campus()))))) with check (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy sessions_delete on public.sessions using ((select is_admin()));
alter policy sessions_insert on public.sessions with check (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'exec_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy sessions_select on public.sessions using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'outreach_lead'::user_role, 'exec_lead'::user_role, 'volunteer_lead'::user_role, 'campus_mgmt_admin'::user_role, 'finance_lead'::user_role])) AND (campus_id = (select auth_campus()))) OR ((select auth.uid()) = ANY (team_members_present)) OR (created_by = (select auth.uid())) OR (EXISTS ( SELECT 1
   FROM session_assignments sa
  WHERE ((sa.session_id = sessions.id) AND (sa.volunteer_id = (select auth.uid())))))));
alter policy sessions_update on public.sessions using (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'exec_lead'::user_role])) AND (campus_id = (select auth_campus()))) OR (created_by = (select auth.uid())))) with check (((select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'exec_lead'::user_role])) AND (campus_id = (select auth_campus()))) OR (created_by = (select auth.uid()))));
alter policy signup_requests_manage on public.signup_requests using ((select is_admin())) with check ((select is_admin()));
alter policy signup_requests_read on public.signup_requests using ((select is_admin()));
alter policy users_delete on public.users using ((select is_super_admin()));
alter policy users_insert on public.users with check ((select is_admin()));
alter policy users_select on public.users using (((id = (select auth.uid())) OR (select is_admin()) OR (campus_id = (select auth_campus()))));
alter policy users_update on public.users using (((id = (select auth.uid())) OR (select is_admin()) OR (((select auth_role()) = 'campus_lead'::user_role) AND (campus_id = (select auth_campus()))))) with check (((id = (select auth.uid())) OR (select is_admin()) OR (((select auth_role()) = 'campus_lead'::user_role) AND (campus_id = (select auth_campus())))));
alter policy applications_manage on public.volunteer_applications using (((select is_admin()) OR ((select auth_role()) = 'campus_lead'::user_role))) with check (((select is_admin()) OR ((select auth_role()) = 'campus_lead'::user_role)));
alter policy applications_read on public.volunteer_applications using (((select is_admin()) OR ((select auth_role()) = 'campus_lead'::user_role)));
alter policy availability_select on public.volunteer_availability using (((volunteer_id = (select auth.uid())) OR (select is_admin()) OR (((select auth_role()) = ANY (ARRAY['campus_lead'::user_role, 'volunteer_lead'::user_role, 'exec_lead'::user_role])) AND (campus_id = (select auth_campus())))));
alter policy availability_write on public.volunteer_availability using (((volunteer_id = (select auth.uid())) OR (select is_admin()))) with check (((volunteer_id = (select auth.uid())) OR (select is_admin())));
